FORMAT: 1A
HOST: http://localhost:8000/api

# Feira API
A Feira API

# Data Structures

## Feira Request (object)
+ nome: PRACA SANTA HELENA (string, required) - Feira name
+ registro: 4003-7 (string, required) - Feira's registro in PMSP organ 
+ long: `-46550164` (string, required) - Longitude
+ lat: `-23558733` (string, required) - Latitude
+ setcens: 355030885000091 (string, required) - Sensitive sector
+ areap: 02236686056 (string, required) - Pondered area
+ logradouro: AV MONS AGNELO (string, required) - Feira common area
+ number: 766 (string, required) - Feira number
+ referencia: TV AV DEP EMILIO CARLOS (string, optional) - Feira reference point
+ distrito_id: 34 (string, required) - Distrito ID
+ sub_pref_id: 11 (string, required) - Subprefeitura ID
+ sub_regiao_id: 11 (string, required) - SubRegiao ID
+ bairro_id: 99 (string, required) - Bairro ID

## Feira Response (object)
+ id: 433(number, fixed) - Unique identifier
+ nome: PRACA SANTA HELENA (string, required) - Feira name
+ registro: 4003-7 (string, fixed) - Feira's registro in PMSP organ 
+ long: `-46550164` (string, required) - Longitude
+ lat: `-23558733` (string, required) - Latitude
+ setcens: 355030885000091 (string, required) - Sensitive sector
+ areap: 02236686056 (string, required) - Pondered area
+ logradouro: AV MONS AGNELO (string, required) - Feira common area
+ number: 766 (string, required) - Feira number
+ referencia: TV AV DEP EMILIO CARLOS (string, optional) - Feira reference point
+ distrito (Distrito Response) - Feira Distrito
+ sub_pref (SubPrefeitura Response) - Feira Subprefeitura
+ sub_regiao (SubRegiao Response) - SubRegiao
+ bairro (Bairro Response) - Feira Bairro

## Distrito Response (object)
+ nome: PENHA (string, required) - Distrito name
+ cod_dist: 60 (string, required) - Distrito codigo as for IBGE

## SubPrefeitura Response (object)
+ nome: MOOCA (string, required) - SubPrefeitura name
+ cod_sub_pref: 25 (string, required) - Sao Paulo's sub town hall code

## Regiao Response (object)
+ nome: Oeste (string, required) - Regiao name

## SubRegiao Response (object)
+ nome: Oeste 1 (string, required) - SubRegiao name
+ regiao (Regiao Response, required) - Regiao

## Bairro Response (object)
+ nome: VL Zelina (string, required) - Bairro name

## Generic Error Response
    + detail: Failed to proccess request (string) - Generic error message

## Validation Error Response
    + field: Field cannot be null (string) - Validation error message
# Feiras [/feiras]
Feira collection


## List Feiras [GET /feiras{?distrito,regiao,nome,bairro,page,per_page}]
List feiras

+ Parameters
    + distrito: PENHA (string, optional) - Distrito name
    + regiao: Oeste (string, optional) - Feira's regiao
    + nome: PRACA SANTA HELENA (string, optional) - Feira name
    + bairro: VL Zelina (string, optional) - Feira bairro
    + page: 1 (string, optional) - Pagination page number
    + per_page: 1 (string, optional) - Pagination itens per page

+ Response 200
    + Attributes
        +  results (array[Feira Response])

+ Response 400
    + Attributes
        + detail: Failed to proccess request (string) - Generic error message
        + field: Field cannot be null (string) - Validation error message


## Get Feira [GET /feiras/{id}]

+ Parameters
    + id: 10928 (string, required) - Feira id

+ Response 200
    + Attributes (Feira Response)

+ Response 404
    + Attributes
        + detail: Not found - (string)

## Create Feira [POST /feiras]

+ Request Create Feira (application/json)
    + Attributes (Feira Request)

+ Response 201
    + Attributes (Feira Response)

+ Response 400
    + Attributes
        + detail: Failed to proccess request (string) - Generic error message
        + field: Field cannot be null (string) - Validation error message

## Update Feira [PATCH /feiras/{id}]

+ Parameters
    + id: 298 (string, required) - Feira id

+ Request (application/json)
    + Attributes (Feira Request)

+ Response 201
    + Attributes (Feira Response)

+ Response 404
    + Attributes
        + detail: Not found - (string)

+ Response 400
    + Attributes
        + detail: Failed to proccess request (string) - Generic error message
        + field: Field cannot be null (string) - Validation error message

## Remove Feira [DELETE /feiras/{id}]
Remove a feira from database

+ Parameters
    + id: 555 (string, required) - Feira id

+ Response 204

+ Response 404
    + Attributes
        + detail: Not found - (string)