FROM python:3.6.8-slim-stretch

ENV PYTHONDONTWRITEBYTECODE='1'
ENV GDAL_LIBRARY_PATH=/usr/lib/libgdal.so

COPY . /app

WORKDIR /app

RUN sh -c "pip install -r requirements_dev.txt"

CMD ["sh", "-c", "/usr/local/bin/gunicorn --reload --access-logfile - -b 0.0.0.0:8000 feira.wsgi"]

EXPOSE 8000