FROM python:3.7.3-slim-stretch

ENV PYTHONDONTWRITEBYTECODE='1'
ENV SNOWBOARD_URL=https://github.com/bukalapak/snowboard/releases/download/v1.7.0/snowboard-v1.7.0.linux-amd64.tar.gz
ENV VANADIA_URL=https://github.com/bukalapak/vanadia/releases/download/v1.1.1/vanadia-v1.1.1.linux-amd64.tar.gz

COPY . /app

WORKDIR /app

RUN apt update -y && \
    apt install make wget -y && \
    apt clean -y && \
    pip install pipenv && \
    pipenv install --dev --system --deploy

RUN wget $SNOWBOARD_URL && \
    tar -zxvf snowboard-v1.7.0.linux-amd64.tar.gz && \
    chmod +x snowboard && \
    mv snowboard /usr/local/bin && \
    rm snowboard-v1.7.0.linux-amd64.tar.gz && \
    wget $VANADIA_URL && \
    tar -zxvf vanadia-v1.1.1.linux-amd64.tar.gz && \
    chmod +x vanadia && \
    mv vanadia /usr/local/bin && \
    rm vanadia-v1.1.1.linux-amd64.tar.gz

RUN mkdir /var/log/app

ENTRYPOINT ["gunicorn", "-c", "gunicorn.py", "feira.wsgi"]

EXPOSE 8000