# Generated by Django 2.1.5 on 2019-01-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=18)),
                ('cod_dist', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('registro', models.CharField(max_length=6, unique=True)),
                ('long', models.CharField(max_length=10)),
                ('lat', models.CharField(max_length=10)),
                ('setcens', models.CharField(max_length=15)),
                ('areap', models.CharField(max_length=13)),
                ('logradouro', models.CharField(max_length=34)),
                ('numero', models.CharField(max_length=5)),
                ('referencia', models.CharField(max_length=24)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairro', to='api.Bairro')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feiras', to='api.Distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubPrefeitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cod_sub_pref', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubRegiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=7)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_regioes', to='api.Regiao')),
            ],
        ),
        migrations.AddField(
            model_name='feira',
            name='sub_pref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feiras', to='api.SubPrefeitura'),
        ),
        migrations.AddField(
            model_name='feira',
            name='sub_regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feiras', to='api.SubRegiao'),
        ),
        migrations.AlterUniqueTogether(
            name='subregiao',
            unique_together={('nome', 'regiao')},
        ),
    ]
