# Generated by Django 2.1.5 on 2019-01-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(name="bairro", options={"ordering": ["-id"]}),
        migrations.AlterModelOptions(name="distrito", options={"ordering": ["-id"]}),
        migrations.AlterModelOptions(name="feira", options={"ordering": ["-id"]}),
        migrations.AlterModelOptions(name="regiao", options={"ordering": ["-id"]}),
        migrations.AlterModelOptions(
            name="subprefeitura", options={"ordering": ["-id"]}
        ),
        migrations.AlterModelOptions(name="subregiao", options={"ordering": ["id"]}),
        migrations.AddIndex(
            model_name="bairro",
            index=models.Index(fields=["nome"], name="bairro_nome_idx"),
        ),
        migrations.AddIndex(
            model_name="distrito",
            index=models.Index(fields=["nome"], name="distrito_nome_idx"),
        ),
        migrations.AddIndex(
            model_name="feira",
            index=models.Index(fields=["nome"], name="feira_nome_idx"),
        ),
        migrations.AddIndex(
            model_name="regiao",
            index=models.Index(fields=["nome"], name="regiao_nome_idx"),
        ),
    ]
