# Generated by Django 2.1.5 on 2019-01-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20190117_2214")]

    operations = [
        migrations.AlterField(
            model_name="feira",
            name="numero",
            field=models.CharField(blank=True, default="", max_length=5),
        )
    ]
