apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: template-app-db-deploy
  labels:
    name: template-app
spec:
  strategy:
    type: Recreat
  selector:
    matchLabels:
      app: template-app-db
  template:
    metadata:
      labels:
        app: template-app-db
    spec:
      containers:
      - image: mdillon/postgis:11-alpine
        name: template-app-db
        livenessProbe:
          tcpSocket:
            port: 5232
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: template-app-db-secret
              key: postgres-password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: template-app-db-secret
              key: postgres-user
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: template-app-db-secret
              key: potgres-db
        ports:
        - containerPort: 5432
          name: db
      restartPolicy: Always
      imagePullPolicy: IfNotPresent