apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: template-app-postgres
  labels:
    app: template-app
    tier: database
spec:
  version: "11.1"
  storageType: Ephemeral
  databaseSecret:
    secretName: template-app-postgres-auth
  init:
    scriptSource:
      configMap:
        name: template-app-pg-init-script